### ISSUE TITLE
Aborting to join measurements does not work

### ISSUE THREAD

**Issue by B-Hartmann** [ZELLMECHANIK-DRESDEN/DCKit#18] opened 2021-07-23 07:15 UTC
DCKit version 0.12.8
Windows 10 version 2004

**Short description:**
Independet from the number of measurement files that were loaded, the button "join measurements" is trying to join measurements, even if you click "cancel" in the following dialog boxes.

**Detailed description:**
When the button "join measurements" is clicked and then the button "cancel" is pressed in the follow-up dialog box to abort the joining process, a window opens asking for an output file path where to save the final joined dataset. If "cancel" is pressed again, one of the following two things happens:
**1.** If there is only one data file loaded in DCKit, an unhandled exception occurs (see image) because there are at least two data sets needed for joining. 
![DCKit_0-12-8_bug_aborting_to_join_measurements](https://user-images.githubusercontent.com/75362246/126747278-06476eec-a541-4e70-813b-115e71a671a5.PNG)

**2.** If there are two or more datasets loaded in DCKit, it will start joining them, creating (at least in my case) a new file called ".rtdc.rtdc" in the folder that was just shown in the "Output file path" dialog.

**Comment by paulmueller** [comment] 2021-07-25 21:45
Duplicate of #14 - sorry, forgot to publish the release.

**Closed by paulmueller** 2021-07-25 21:45 UTC
